# @package _global_
defaults:
  - /dataset: sort_of_clevr/default
  - /model: sort_of_clevr/busnet
  - /callbacks: sort_of_clevr/default
  - _self_

train:
  n_steps: 1000
  train_bs: 256
  val_bs: 1024
  
  early_stop_metric: loss
  early_stop_big_is_better: false
  early_stop_patience: 10
  early_stop_min_delta: 0.0

  loader_mode: gpu_cached
  mixed_precision: 'no'
  compile_model: true
  grad_accum: 1
  grad_clip: 1.0
  num_workers: 0

optim:
  optimiser: adamw
  lr: 3e-4
  weight_decay: 0.0
  lr_scheduler: warmup_cosine
  lr_scheduler_params:
    warmup_steps: 2_000

logging:
  train_log_interval: 100
  eval_log_interval: 100
  info_metrics: [loss, accuracy]
  save_best: false

wandb:
  enabled: true
  project_name: sort_of_clevr
  entity: niks_priv
  run_name: null
  tags: []