
defaults:
  - config_schema
  - _self_
  - task: sort_of_clevr
  - optional experiment: null

# include config here that is shared between task, otherwise task will override
train:
  seed: 0

hydra:
  run:
    dir: outputs/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/${dataset.name}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false
